#!/bin/bash
# Fix below
# PostgreSQL install directory PGHOME
PGHOME_FOR_TEST=~/pgsql12
# connection port number
PORT=5432
# Fix above

PSQLBIN=$PGHOME_FOR_TEST/bin
TSURUGI_METADATA_HOME=$HOME/.local
TSURUGI_METADATA_DIR=tsurugi/metadata
TSURUGI_METADATA_STORAGE_PATH=$TSURUGI_METADATA_HOME/$TSURUGI_METADATA_DIR

# tests except REGRESS variable written in Makefile
TEST_SQL_OTHER_COMPONENT_ERROR="sql/other_component_error.sql"
TEST_RESULTS_DIR="results"
EXPECTED_DIR="expected/extra"
FILE_NAME_TABLES_METADATA=tables.json
FILE_NAME_DATATYPES_METADATA=datatypes.json
FILE_NAME_OID=oid
OK_COUNT=0
FAILED_COUNT=0

# 1. test when ogawayama-server is not started
TESTCASE_NAME_OGAWAYAMA="ogawayama_server_not_started"
TEST_RESULTS_OUTPUT_FILE_OGAWAYAMA="${TESTCASE_NAME_OGAWAYAMA}.out"

echo "[ RUN    ] TESTCASE NAME: ${TESTCASE_NAME_OGAWAYAMA}"
rm -rf $TSURUGI_METADATA_STORAGE_PATH
ogawayama-cli -terminate
$PSQLBIN/psql -p $PORT -a postgres < $TEST_SQL_OTHER_COMPONENT_ERROR > $TEST_RESULTS_DIR/$TEST_RESULTS_OUTPUT_FILE_OGAWAYAMA 2>&1

diff $TEST_RESULTS_DIR/$TEST_RESULTS_OUTPUT_OGAWAYAMA $EXPECTED_DIR/$TESTCASE_NAME_OGAWAYAMA/$TEST_RESULTS_OUTPUT_FILE_OGAWAYAMA
if [ $? -ne 0 ]; then
    FAILED_COUNT=`expr $FAILED_COUNT + 1`
    echo "[ FAILED ] $TEST_RESULTS_OUTPUT_FILE_OGAWAYAMA"
else
    OK_COUNT=`expr $OK_COUNT + 1`
    echo "[     OK ] $TEST_RESULTS_OUTPUT_FILE_OGAWAYAMA"
fi

diff $TSURUGI_METADATA_STORAGE_PATH/$FILE_NAME_TABLES_METADATA $EXPECTED_DIR/$TESTCASE_NAME_OGAWAYAMA/$TSURUGI_METADATA_DIR/$FILE_NAME_TABLES_METADATA
if [ $? -ne 0 ]; then
    FAILED_COUNT=`expr $FAILED_COUNT + 1`
    echo "[ FAILED ] $FILE_NAME_TABLES_METADATA"
else
    OK_COUNT=`expr $OK_COUNT + 1`
    echo "[     OK ] $FILE_NAME_TABLES_METADATA"
fi

# 2. test when frontend fails to load metadata
for FILE_NAME in $FILE_NAME_TABLES_METADATA $FILE_NAME_DATATYPES_METADATA $FILE_NAME_OID
do
    TESTCASE_NAME_METADATA="fails_to_load"
    TEST_RESULTS_OUTPUT_FILE_METADATA="${TESTCASE_NAME_METADATA}_${FILE_NAME}.out"

    echo "[ RUN    ] TESTCASE NAME: ${TESTCASE_NAME_METADATA}_${FILE_NAME}"

    rm -rf $TSURUGI_METADATA_STORAGE_PATH
    mkdir -p $TSURUGI_METADATA_STORAGE_PATH
    touch $TSURUGI_METADATA_STORAGE_PATH/$FILE_NAME_TABLES_METADATA
    touch $TSURUGI_METADATA_STORAGE_PATH/$FILE_NAME_DATATYPES_METADATA
    touch $TSURUGI_METADATA_STORAGE_PATH/$FILE_NAME_OID
    sudo chown root:root $TSURUGI_METADATA_STORAGE_PATH/$FILE_NAME
    echo "ls -la ${TSURUGI_METADATA_STORAGE_PATH}/"
    ls -la $TSURUGI_METADATA_STORAGE_PATH/
    ogawayama-cli -terminate
    ogawayama-server -remove_shm > ogawayama-server.out 2>&1 &
    $PSQLBIN/psql -p $PORT -a postgres < $TEST_SQL_OTHER_COMPONENT_ERROR > $TEST_RESULTS_DIR/$TEST_RESULTS_OUTPUT_FILE_METADATA 2>&1
    
    diff $TEST_RESULTS_DIR/$TEST_RESULTS_OUTPUT_METADATA $EXPECTED_DIR/$TESTCASE_NAME_METADATA/$TEST_RESULTS_OUTPUT_FILE_METADATA
    if [ $? -ne 0 ]; then
        FAILED_COUNT=`expr $FAILED_COUNT + 1`
        echo "[ FAILED ] $TEST_RESULTS_OUTPUT_FILE_METADATA"
    else
        OK_COUNT=`expr $OK_COUNT + 1`
        echo "[     OK ] $TEST_RESULTS_OUTPUT_FILE_METADATA"
    fi
    
    diff $TSURUGI_METADATA_STORAGE_PATH/$FILE_NAME_TABLES_METADATA $EXPECTED_DIR/$TESTCASE_NAME_METADATA/$TSURUGI_METADATA_DIR/$FILE_NAME_TABLES_METADATA
    if [ $? -ne 0 ]; then
        FAILED_COUNT=`expr $FAILED_COUNT + 1`
        echo "[ FAILED ] $FILE_NAME_TABLES_METADATA"
    else
        OK_COUNT=`expr $OK_COUNT + 1`
        echo "[     OK ] $FILE_NAME_TABLES_METADATA"
    fi
done

echo "[========]"
echo "[ FAILED ] $FAILED_COUNT tests"
echo "[ PASSED ] $OK_COUNT tests"

rm -rf $TSURUGI_METADATA_STORAGE_PATH
