' =========================================================
'
' =========================================================
@startuml Command_detail
left to right direction
skinparam defaultFontSize 20

package "manager/message-broker" {
  abstract class Receiver {
    {abstract} public virtual Status receive_message(Message* message) = 0;
  }

  abstract class Message{
  	{field} private MessageId id;　　　　　　　　　
  	{field} private uint64_t object_id;　　　　
  	{field} private std::vector<Receiver*> receivers;　
  	{field} private std::string message_type_name;
    {method}// C'tor
  	{method}public Message(MessageId id, uint64_t object_id, std::string message_type_name)
    {method}
    {method}// set receiver
  	{method}public void set_receiver(Receiver *receiver_)
    {method}
    {method}// getter
  	{method}public MessageId  get_id();
  	{method}public uint64_t    get_object_id();
  	{method}public std::string get_message_type_name();
  }

  class CreateTableMessage {
    {method}// C'tor
  	{method}public CreateTableMessage(uint64_t object_id)
  }

  class MessageBroker {
    public Status send_message(Message* message);
  }
}

package ogawayama {
  class "stub::Transaction" {
    public Status receive_message(Message* message)
  }
}

package OLAP_EntryPoint {
  class OlapReceiver {
    public Status receive_message(Message* message)
  }
}

package frontend {
  class Client {
  }

}

"stub::Transaction" -|> Receiver

MessageBroker --> Message
Message --> Receiver

Message <|- CreateTableMessage

Client --> CreateTableMessage : create
Client -> "stub::Transaction" : create
MessageBroker <- Client : create

OlapReceiver -|> Receiver
Client -> OlapReceiver : create

@enduml
