@startuml

Command <|-- CreateTableCommand

abstract class Command{
	{field} private int id; //コマンドの種類を特定するID ex)0
	{field} private string name; //コマンドの種類の名前 ex)"CREATE TABLE"
	{field} private int table_id; // TableメタデータオブジェクトのテーブルID

	{abstract} public explicit Command(int id, string name, int table_id) //コンストラクタ
	{abstract} public virtual ~Command() //デストラクタ
    {abstract} private virtual int execute(); //実行エンジンで利用する。frontendでは利用しない。
}

class CreateTableCommand{
	public CreateTableCommand(int id, string name, int table_id)
	public ~CreateTableCommand()
    private int execute();
}

@enduml
