' =========================================================
' 概要シーケンス
' =========================================================
@startuml テーブル定義シーケンス概要
hide footbox

control PostgreSQL as pg
control frontend as frontend
control "ogawayama-stub" as stub
entity "metadata-manager" as metadata

activate pg
  pg -> frontend : hook DDL command
  activate frontend
    frontend -> metadata : write DDL parameters
    frontend -> stub : message(DDL command)
    activate stub
      stub -> metadata : read DDL parameters
      stub -> stub : schema defined on Tsurugi
      stub -> metadata : update DDL parameters
      frontend <<-- stub
      deactivate stub
    pg <<-- frontend
  deactivate frontend
deactivate pg
@enduml
