@startuml
title テーブル定義シーケンス詳細
hide footbox

actor 利用者
boundary PostgreSQL
control "alt_utility/alt_utility.c"
control "alt_utility/create_table.cpp"
control "alt_utility/tablecmds.cpp"
control "metadata-manager"
database datatypes.json
database tables.json
control ogawayama
control umikongo

利用者 -> PostgreSQL : テーブル定義要求()
activate PostgreSQL
note right
CREATE TABLE文
end note

PostgreSQL -> "alt_utility/alt_utility.c" : static void tsurugi_ProcessUtilitySlow(...)
activate "alt_utility/alt_utility.c"

"alt_utility/alt_utility.c" -> "alt_utility/create_table.cpp" : create_table((CreateStmt *)stmt)
activate "alt_utility/create_table.cpp"

"alt_utility/create_table.cpp" -> "alt_utility/tablecmds.cpp" : define_relation((CreateStmt *)stmt)
activate "alt_utility/tablecmds.cpp"

create "metadata-manager"

alt metadata-managerインスタンスが生成されていない
"alt_utility/tablecmds.cpp" -> "metadata-manager" : metadata-managerインスタンス生成
activate "metadata-manager"

alt datatypes.jsonが生成されていない
    create datatypes.json
    "metadata-manager" -> datatypes.json : datatypes.jsonファイル生成
end

"alt_utility/tablecmds.cpp" -> "metadata-manager" : metadata-managerにテーブル情報を送信

alt tables.jsonが生成されていなければ
    create tables.json
    "metadata-manager" -> tables.json
end
"metadata-manager" -> tables.json : テーブル情報をjsonに書き出し
"metadata-manager" --> "alt_utility/tablecmds.cpp"
deactivate "metadata-manager"

"alt_utility/tablecmds.cpp" --> "alt_utility/create_table.cpp"
deactivate "alt_utility/tablecmds.cpp"

"alt_utility/create_table.cpp" -> ogawayama : Message(コマンドの種類, テーブル名, その他パラメーター)
activate ogawayama
note right
テーブル定義要求

ogawayamaへのパラメーターの渡し方
（関数名・型・パラメーター・デザインパターンなど）
については、すべてノーチラス・テクノロジーズ様に決定していただきたいです。
end note

ogawayama -> "metadata-manager" : テーブル情報取得
activate "metadata-manager"

"metadata-manager" -> tables.json : テーブル情報取得
tables.json --> "metadata-manager" : テーブル情報
"metadata-manager" --> ogawayama : テーブル情報
deactivate "metadata-manager"

ogawayama -> umikongo : テーブル定義要求
activate umikongo
umikongo --> ogawayama
deactivate umikongo

ogawayama --> "alt_utility/create_table.cpp"

"alt_utility/create_table.cpp" -> ogawayama : commit()
ogawayama --> "alt_utility/create_table.cpp"

"alt_utility/create_table.cpp" -> ogawayama : end()
ogawayama --> "alt_utility/create_table.cpp"
deactivate ogawayama

"alt_utility/create_table.cpp" --> "alt_utility/alt_utility.c"
deactivate "alt_utility/create_table.cpp"

"alt_utility/alt_utility.c" --> PostgreSQL
deactivate "alt_utility/alt_utility.c"

PostgreSQL --> 利用者
deactivate PostgreSQL

@enduml
