CREATE DATABASE test TEMPLATE = template0 ENCODING = 'UTF8' LC_COLLATE = 'C' LC_CTYPE = 'en_US.utf8';

\c test

CREATE SCHEMA tmp;

-- type error not supported
CREATE TABLE tmp.orders_type_error (
  o_w_id int NOT NULL,
  o_d_id int NOT NULL,
  o_id int NOT NULL,
  o_c_id int NOT NULL,
  o_carrier_id int,
  o_ol_cnt decimal(2,0) NOT NULL,
  o_all_local decimal(1,0) NOT NULL,
  o_entry_d timestamp NOT NULL,
  PRIMARY KEY (o_w_id,o_d_id,o_id)
) tablespace tsurugi;

-- UNIQUE table constraint
CREATE TABLE tmp.orders_unique_tc (
  o_w_id int NOT NULL,
  o_d_id int NOT NULL,
  o_id int NOT NULL,
  o_c_id int NOT NULL,
  o_carrier_id int,
  o_ol_cnt double precision NOT NULL, -- decimal(2,0) NOT NULL
  o_all_local double precision NOT NULL, -- decimal(1,0) NOT NULL
  o_entry_d char(24) NOT NULL, -- timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
  PRIMARY KEY (o_w_id,o_d_id,o_id),
  UNIQUE (o_w_id,o_d_id,o_c_id,o_id)
) tablespace tsurugi;

-- DEFAULT column constraint
CREATE TABLE tmp.orders_default_cc (
  o_w_id int NOT NULL,
  o_d_id int NOT NULL,
  o_id int NOT NULL,
  o_c_id int NOT NULL,
  o_carrier_id int DEFAULT NULL,
  o_ol_cnt double precision NOT NULL, -- decimal(2,0) NOT NULL
  o_all_local double precision NOT NULL, -- decimal(1,0) NOT NULL
  o_entry_d char(24) NOT NULL, -- timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
  PRIMARY KEY (o_w_id,o_d_id,o_id)
) tablespace tsurugi;

-- referred by FOREIGN KEY constraint
CREATE TABLE tmp.customer (
  c_w_id int NOT NULL,
  c_d_id int NOT NULL,
  c_id int NOT NULL,
  c_discount double precision NOT NULL, -- decimal(4,4) NOT NULL
  c_credit char(2) NOT NULL,
  c_last varchar(16) NOT NULL,
  c_first varchar(16) NOT NULL,
  c_credit_lim double precision NOT NULL, -- decimal(12,2) NOT NULL
  c_balance double precision NOT NULL, -- decimal(12,2) NOT NULL
  c_ytd_payment float NOT NULL,
  c_payment_cnt int NOT NULL,
  c_delivery_cnt int NOT NULL,
  c_street_1 varchar(20) NOT NULL,
  c_street_2 varchar(20) NOT NULL,
  c_city varchar(20) NOT NULL,
  c_state char(2) NOT NULL,
  c_zip char(9) NOT NULL,
  c_phone char(16) NOT NULL,
  c_since char(24) NOT NULL, -- timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
  c_middle char(2) NOT NULL,
  c_data varchar(500) NOT NULL,
  PRIMARY KEY (c_w_id,c_d_id,c_id)
) tablespace tsurugi;

-- FOREIGN KEY constraint
CREATE TABLE tmp.orders_fkey (
  o_w_id int NOT NULL,
  o_d_id int NOT NULL,
  o_id int NOT NULL,
  o_c_id int NOT NULL,
  o_carrier_id int,
  o_ol_cnt double precision NOT NULL, -- decimal(2,0) NOT NULL
  o_all_local double precision NOT NULL, -- decimal(1,0) NOT NULL
  o_entry_d char(24) NOT NULL, -- timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
  PRIMARY KEY (o_w_id,o_d_id,o_id),
  FOREIGN KEY(o_w_id,o_d_id,o_c_id) REFERENCES customer(c_w_id,c_d_id,c_id)
) tablespace tsurugi;

-- CHECK column constraint
CREATE TABLE tmp.distributors_check_cc (
    did     integer CHECK (did > 100),
    name    varchar(40)
) tablespace tsurugi;

-- CHECK table constraint
CREATE TABLE tmp.distributors_check_tc (
    did     integer,
    name    varchar(40),
    CONSTRAINT con1 CHECK (did > 100 AND name <> '')
) tablespace tsurugi;

-- GENERATED BY
CREATE TABLE tmp.distributors_generated_by (
     did    integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
     name   varchar(40) NOT NULL
) tablespace tsurugi;

-- UNIQUE column constraint
CREATE TABLE tmp.distributors_unique_cc (
    did     integer,
    name    varchar(40) UNIQUE
) tablespace tsurugi;

-- WITH clause of table
CREATE TABLE tmp.distributors_table_with (
    did     integer,
    name    varchar(40)
)
WITH (fillfactor=70) tablespace tsurugi;

-- column WITH clause
CREATE TABLE tmp.distributors_column_with (
    did     integer,
    name    varchar(40),
    UNIQUE(name) WITH (fillfactor=70)
) tablespace tsurugi;

-- EXCLUDE USING
CREATE TABLE tmp.distributotrs_exclude_using (
    name varchar,
    age integer,
    EXCLUDE USING gist (age WITH <>)
) tablespace tsurugi;

-- OF clause
CREATE TYPE employee_type AS (name text, salary numeric);

CREATE TABLE tmp.employees OF employee_type (
    PRIMARY KEY (name),
    salary
) tablespace tsurugi;

-- PARTITION BY RANGE
CREATE TABLE tmp.measurement (
    logdate         varchar(24) not null,
    peaktemp        int,
    unitsales       int
) PARTITION BY RANGE (logdate) tablespace tsurugi;

CREATE TABLE tmp.measurement_y2016m07
PARTITION OF measurement
FOR VALUES FROM ('2016-07-01') TO ('2016-08-01') tablespace tsurugi;

-- PARTITION BY LIST
CREATE TABLE tmp.cities (
    city_id      bigint not null,
    name         varchar not null,
    population   bigint
) PARTITION BY LIST (name) tablespace tsurugi;

CREATE TABLE tmp.cities_ab
PARTITION OF cities
FOR VALUES IN ('a', 'b') tablespace tsurugi;

-- PARTITION BY HASH
CREATE TABLE tmp.orders_partition_by_hash (
    order_id     bigint not null,
    cust_id      bigint not null,
    status       varchar
) PARTITION BY HASH (order_id) tablespace tsurugi;

CREATE TABLE tmp.orders_p1 PARTITION OF orders_partition_by_hash
FOR VALUES WITH (MODULUS 4, REMAINDER 0) tablespace tsurugi;

-- DEFERRABLE INITIALLY DEFERRED
CREATE TABLE tmp.deferrable_initially_deferred(
    id integer NOT NULL,
    CONSTRAINT posts2_pk PRIMARY KEY (id) DEFERRABLE INITIALLY DEFERRED
) tablespace tsurugi;

-- DEFERRABLE INITIALLY IMMEDIATE
CREATE TABLE tmp.deferrable_initially_immediate(
    id integer NOT NULL,
    CONSTRAINT posts2_pk PRIMARY KEY (id) DEFERRABLE INITIALLY IMMEDIATE
) tablespace tsurugi;

-- DEFERRABLE
CREATE TABLE tmp.deferrable(
    id integer NOT NULL,
    CONSTRAINT posts2_pk PRIMARY KEY (id) DEFERRABLE
) tablespace tsurugi;

-- NOT DEFERRABLE
CREATE TABLE tmp.not_deferrable(
    id integer NOT NULL,
    CONSTRAINT posts2_pk PRIMARY KEY (id) NOT DEFERRABLE
) tablespace tsurugi;

DROP SCHEMA tmp CASCADE;

\c postgres

DROP DATABASE test;
