#!/bin/bash
PSQLHOME_FOR_TEST=~/pgsql12cov
PSQLBIN=$PSQLHOME_FOR_TEST/bin
TSURUGI_METADATA=tsurugi_metadata
TSURUGI_METADATA_HOME=$PSQLHOME_FOR_TEST/data/$TSURUGI_METADATA

DATATYPES=datatypes.json
OID=oid
TABLES=tables.json
PORT=5438

for TESTCASE in otable_of_constr ch-benchmark-ddl alternative happy unhappy
do
    rm -rf $TSURUGI_METADATA_HOME

    EXPECTED=$TESTCASE/expected
    TEST_SQL=$TESTCASE/$TESTCASE.sql
    TEST_RESULTS_OUTPUT=$EXPECTED/$TESTCASE.out
    TEST_RESULTS_OUTPUT_TSURUGI_METADATA=$EXPECTED/$TSURUGI_METADATA

    $PSQLBIN/psql -p $PORT -a postgres < $TEST_SQL > $TEST_RESULTS_OUTPUT 2>&1

    diff $TEST_RESULTS_OUTPUT_TSURUGI_METADATA/$DATATYPES $TSURUGI_METADATA_HOME/$DATATYPES
    diff $TEST_RESULTS_OUTPUT_TSURUGI_METADATA/$OID       $TSURUGI_METADATA_HOME/$OID
    diff $TEST_RESULTS_OUTPUT_TSURUGI_METADATA/$TABLES    $TSURUGI_METADATA_HOME/$TABLES
done
