' =========================================================
'
' =========================================================
@startuml Status
left to right direction

package "manager/message-broker" {
namespace manager::message {

    abstract class Status<T>
    {
        {method}//C'tor
        {method}public Status(ErrorCode error_code, T sub_error_code, ReceiverId receiver_id)
        {method}//getter
        {method}public ErrorCode get_error_code()
        {method}public T get_sub_error_code()
        {method}public ReceiverId get_receiver_id()
        {field}private ErrorCode error_code
        {field}private T sub_error_code
        {field}private ReceiverId receiver_id
    }

    class AllReceiversSuccessStatus<ErrorCode>
    {
    }

    class OgawayamaStatus<T>
    {
        {method}//C'tor
        {method}public OgawayamaStatus(ErrorCode error_code, T sub_error_code)
    }

    class OlapStatus<T>
    {
        {method}//C'tor
        {method}public OlapStatus(ErrorCode error_code, T sub_error_code)
    }

AllReceiversSuccessStatus -|> Status
OgawayamaStatus -|> Status
OlapStatus -|> Status
}
}

@enduml
