' =========================================================
'
' =========================================================
@startuml Status
left to right direction

package "manager/message-broker" {
namespace manager::message {

    abstract class Status<T>
    {
        {method}//C'tor
        {method}public Status(ErrorCode error_code, T sub_error_code, ComponentId component_id)
        {method}//getter
        {method}public ErrorCode get_error_code()
        {method}public T get_sub_error_code()
        {method}public ComponentId get_component_id()
        {field}private ErrorCode error_code //概要エラーコード
        {field}private T sub_error_code //詳細エラーコード
        {field}private ComponentId component_id //コンポーネントID
    }

    class AllComponentsSuccessStatus<ErrorCode>
    {
    }

    note top of AllComponentsSuccessStatus : すべてのReceiverが成功時に返される。

    class OgawayamaStatus<T>
    {
        {method}//C'tor
        {method}public OgawayamaStatus(ErrorCode error_code, T sub_error_code)
    }

    note top of OgawayamaStatus : ogawayamaのstub::Transactionが返すエラーコード

    class OlapStatus<T>
    {
        {method}//C'tor
        {method}public OlapStatus(ErrorCode error_code, T sub_error_code)
    }

    note top of OlapStatus : OlapReceiverが返すエラーコード

AllComponentsSuccessStatus -|> Status
OgawayamaStatus -|> Status
OlapStatus -|> Status
}
}

@enduml
