/* DDL */
CREATE TABLE t1(c1 INTEGER NOT NULL PRIMARY KEY) TABLESPACE tsurugi;
CREATE FOREIGN TABLE t1(c1 INTEGER NOT NULL) SERVER ogawayama;

CREATE TABLE t2(c1 INTEGER NOT NULL PRIMARY KEY, c2 BIGINT, c3 DOUBLE PRECISION) TABLESPACE tsurugi;
CREATE FOREIGN TABLE t2(c1 INTEGER NOT NULL, c2 BIGINT, c3 DOUBLE PRECISION) SERVER ogawayama;

/* DML */
SELECT * FROM t1;
INSERT INTO t1 (c1) VALUES (1);
SELECT * FROM t1;

SELECT * FROM t2;
INSERT INTO t2 (c1, c2, c3) VALUES (1, 100, 1.1);
INSERT INTO t2 (c1, c2, c3) VALUES (2, 200, 2.2);
SELECT * FROM t2;

SELECT * FROM t1;
INSERT INTO t1 (c1) VALUES (10);
INSERT INTO t1 (c1) VALUES (100);
SELECT * FROM t1;

SELECT * FROM t2;
UPDATE t2 SET c2 = c2+10;
UPDATE t2 SET c3 = c3+1.1 WHERE c2 = 110;
SELECT * FROM t2;

SELECT * FROM t1;
DELETE FROM t1 WHERE c1 = 10;
SELECT * FROM t1;

/* DDL */
DROP TABLE t1;
DROP TABLE t2;

DROP FOREIGN TABLE t1;
DROP FOREIGN TABLE t2;
