CREATE DATABASE test TEMPLATE = template0 ENCODING = 'UTF8' LC_COLLATE = 'C' LC_CTYPE = 'en_US.utf8';

\c test

CREATE EXTENSION tsurugi_fdw;
CREATE SERVER ogawayama FOREIGN DATA WRAPPER tsurugi_fdw;

/* DDL */
CREATE TABLE t1(c1 INTEGER NOT NULL PRIMARY KEY) TABLESPACE tsurugi;
CREATE FOREIGN TABLE t1(c1 INTEGER NOT NULL) SERVER ogawayama;

CREATE TABLE t2(c1 INTEGER NOT NULL PRIMARY KEY, c2 BIGINT, c3 DOUBLE PRECISION) TABLESPACE tsurugi;
CREATE FOREIGN TABLE t2(c1 INTEGER NOT NULL, c2 BIGINT, c3 DOUBLE PRECISION) SERVER ogawayama;

/* DML */
SELECT * FROM t1;
INSERT INTO t1 (cl) VALUES (1);
SELECT * FROM t1;

SELECT * FROM t2;
INSERT INTO t2 (cl, c2, c3) VALUES (1, 100, 1.1);
INSERT INTO t2 (cl, c2, c3) VALUES (2, 200, 2.2);
SELECT * FROM t2;

SELECT * FROM t1;
INSERT INTO t1 (cl) VALUES (10);
INSERT INTO t1 (cl) VALUES (100);
SELECT * FROM t1;

SELECT * FROM t2;
UPDATE t2 SET c2 = c2+10;
UPDATE t2 SET c3 = c3+1.1 WHERE c2 = 110;
SELECT * FROM t2;

SELECT * FROM t1;
DELETE FROM t1 WHERE c1 = 10;
SELECT * FROM t1;

/* Drop tables */
DROP FOREIGN TABLE t1;
DROP TABLE t1_dummy;

DROP FOREIGN TABLE t2;
DROP TABLE t2_dummy;

\c postgres

DROP DATABASE test;
