CREATE EXTENSION IF NOT EXISTS tsurugi_fdw;
CREATE SERVER IF NOT EXISTS tsurugidb FOREIGN DATA WRAPPER tsurugi_fdw;
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS bigint1');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS char_length_1');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS char_length_10');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS double1');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS employee_1');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS employee_2');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS employee_i');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS fdw_test_table');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS fdw_test_table_1');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS fdw_test_table_2');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS fdw_test_table_3');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS fdw_test_table_a');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS fdw_test_table_A');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS fdw_test_Table_A');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS fdw_test_TABLE_B');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS fdw_test_table_name2_________3_________4_________5_________6__');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS fdw_test_table_name2_________3_________4_________5_________6___');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS fdw_test_table_name2_________3_________4_________5_________6____');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS fdw_test_type_datetime');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS fdw_test_type_invalid');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS fdw_test_type_num');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS fdw_test_type_str');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS insert_select_happy');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS integer1');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS real1');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS re_table1');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS re_table2');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS ri_table1');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS ri_table2');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS t1_create_table');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS t1_prepare_select_statement');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS t1_select_statement');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS t1_user_management');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS t2_create_table');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS t2_prepare_select_statement');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS t2_select_statement');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS t2_user_management');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS t3_create_index');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS t3_prepare_select_statement');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS t3_select_statement');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS t3_user_management');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS t4_create_index');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS tg_numeric');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS tg_numeric_s0');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS tg_numeric_s38');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS tg_table');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS tg_temporal_literal');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS tg_timedate');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS tg_timestamptz');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS tg_timetz');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS udf_table1');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS udf_test_table_1');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS Udf_Test_Table_1');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS udf_test_table_2');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS UDF_test_table_2');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS udf_test_table_3');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS udf_test_table_4');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS udf_test_table_bigint');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS udf_test_table_binary');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS udf_test_table_binary_l');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS udf_test_table_binary_varying');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS udf_test_table_binary_varying_l');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS udf_test_table_boolean');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS udf_test_table_bytea');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS udf_test_table_char');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS udf_test_table_character');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS udf_test_table_character_l');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS udf_test_table_character_len');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS udf_test_table_character_varying');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS udf_test_table_character_varying_l');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS udf_test_table_character_varying_len');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS udf_test_table_char_l');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS udf_test_table_char_len');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS udf_test_table_char_varying');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS udf_test_table_char_varying_l');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS udf_test_table_char_varying_len');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS udf_test_table_date');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS udf_test_table_decimal');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS udf_test_table_decimal_max');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS udf_test_table_decimal_p');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS udf_test_table_decimal_p2');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS udf_test_table_decimal_ps');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS udf_test_table_decimal_ps2');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS udf_test_table_double');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS udf_test_table_double_precision');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS udf_test_table_float');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS udf_test_table_int');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS udf_test_table_matched_1');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS udf_test_table_numeric_p');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS udf_test_table_real');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS udf_test_table_remote_1');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS udf_test_table_smallint');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS udf_test_table_time');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS udf_test_table_time_p');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS udf_test_table_timestamp');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS udf_test_table_timestamp_p');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS udf_test_table_timestamptz');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS udf_test_table_timestamp_without_time_zone');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS udf_test_table_timestamp_with_time_zone');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS udf_test_table_timestamp_with_time_zone_p');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS udf_test_table_timetz');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS udf_test_table_time_without_time_zone');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS udf_test_table_time_with_time_zone');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS udf_test_table_time_with_time_zone_p');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS udf_test_table_unmatched_1');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS udf_test_table_unmatched_2');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS udf_test_table_varbinary');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS udf_test_table_varbinary_l');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS udf_test_table_varchar');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS udf_test_table_varchar_l');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS udf_test_table_varchar_len');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS update_delete_bigint1');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS update_delete_char1');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS update_delete_double1');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS update_delete_int1');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS update_delete_real1');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS update_delete_varchar1');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS varchar_length_1');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS varchar_length_10');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS weather');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS wp_table1');
SELECT tg_execute_ddl('tsurugidb', 'DROP TABLE IF EXISTS wp_table2');
DO $$
DECLARE
    TABLE_MAX CONSTANT INT := 1000;
    i INT;
BEGIN
    FOR i IN 1..TABLE_MAX LOOP
        EXECUTE format(
            'SELECT tg_execute_ddl(''tsurugidb'', ''DROP TABLE IF EXISTS fdw_test_table_%s'')',
            to_char(i, 'FM0000'));
        EXECUTE format(
            'SELECT tg_execute_ddl(''tsurugidb'', ''DROP TABLE IF EXISTS udf_test_table_%s'')',
            to_char(i, 'FM0000'));
    END LOOP;
END $$;
